/*
 * Voucherify API
 *
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Voucherify.Client.OpenAPIDateConverter;

namespace Voucherify.Model
{
    /// <summary>
    /// Contains the order details associated with the redemption.
    /// </summary>
    [DataContract(Name = "ClientRedemptionsRedeemResponseBodyOrder")]
    public partial class ClientRedemptionsRedeemResponseBodyOrder : IValidatableObject
    {
        /// <summary>
        /// The order status.
        /// </summary>
        /// <value>The order status.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum CREATED for value: CREATED
            /// </summary>
            [EnumMember(Value = "CREATED")]
            CREATED = 1,

            /// <summary>
            /// Enum PAID for value: PAID
            /// </summary>
            [EnumMember(Value = "PAID")]
            PAID = 2,

            /// <summary>
            /// Enum CANCELED for value: CANCELED
            /// </summary>
            [EnumMember(Value = "CANCELED")]
            CANCELED = 3,

            /// <summary>
            /// Enum FULFILLED for value: FULFILLED
            /// </summary>
            [EnumMember(Value = "FULFILLED")]
            FULFILLED = 4
        }


        /// <summary>
        /// The order status.
        /// </summary>
        /// <value>The order status.</value>

        [DataMember(Name = "status", EmitDefaultValue = true)]
        public StatusEnum? Status
        {
            get{ return _Status;}
            set
            {
                _Status = value;
                _flagStatus = true;
            }
        }
        private StatusEnum? _Status;
        private bool _flagStatus;

        /// <summary>
        /// Returns false as Status should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeStatus()
        {
            return _flagStatus;
        }
        /// <summary>
        /// The type of the object represented by JSON.
        /// </summary>
        /// <value>The type of the object represented by JSON.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ObjectEnum
        {
            /// <summary>
            /// Enum Order for value: order
            /// </summary>
            [EnumMember(Value = "order")]
            Order = 1
        }


        /// <summary>
        /// The type of the object represented by JSON.
        /// </summary>
        /// <value>The type of the object represented by JSON.</value>

        [DataMember(Name = "object", EmitDefaultValue = true)]
        public ObjectEnum? Object
        {
            get{ return _Object;}
            set
            {
                _Object = value;
                _flagObject = true;
            }
        }
        private ObjectEnum? _Object;
        private bool _flagObject;

        /// <summary>
        /// Returns false as Object should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeObject()
        {
            return _flagObject;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="ClientRedemptionsRedeemResponseBodyOrder" /> class.
        /// </summary>
        /// <param name="id">Unique ID assigned by Voucherify of an existing order that will be linked to the redemption of this request..</param>
        /// <param name="sourceId">Unique source ID of an existing order that will be linked to the redemption of this request..</param>
        /// <param name="status">The order status..</param>
        /// <param name="amount">This is the sum of the order items&#39; amounts. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00)..</param>
        /// <param name="initialAmount">This is the sum of the order items&#39; amounts before any discount or other effect (e.g. add missing units) is applied. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00)..</param>
        /// <param name="discountAmount">Sum of all order-level discounts applied to the order. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00)..</param>
        /// <param name="itemsDiscountAmount">Sum of all product-specific discounts applied to the order. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00)..</param>
        /// <param name="totalDiscountAmount">Sum of all order-level AND all product-specific discounts applied to the order. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00)..</param>
        /// <param name="totalAmount">Order amount after undoing all the discounts through the rollback redemption. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00)..</param>
        /// <param name="appliedDiscountAmount">This field shows the order-level discount applied. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00)..</param>
        /// <param name="itemsAppliedDiscountAmount">Sum of all product-specific discounts applied in a particular request. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).   &#x60;sum(items, i &#x3D;&gt; i.applied_discount_amount)&#x60;.</param>
        /// <param name="totalAppliedDiscountAmount">Sum of all order-level AND all product-specific discounts applied in a particular request. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).   &#x60;total_applied_discount_amount&#x60; &#x3D; &#x60;applied_discount_amount&#x60; + &#x60;items_applied_discount_amount&#x60;.</param>
        /// <param name="metadata">A set of custom key/value pairs that you can attach to an order. It can be useful for storing additional information about the order in a structured format. It can be used to define business validation rules or discount formulas..</param>
        /// <param name="varObject">The type of the object represented by JSON. (default to ObjectEnum.Order).</param>
        /// <param name="createdAt">Timestamp representing the date and time when the order was created. The value is shown in the ISO 8601 format..</param>
        /// <param name="updatedAt">Timestamp representing the date and time when the order was last updated in ISO 8601 format..</param>
        /// <param name="customerId">Unique customer identifier of the customer making the purchase. The ID is assigned by Voucherify..</param>
        /// <param name="referrerId">Unique referrer ID..</param>
        /// <param name="customer">customer.</param>
        /// <param name="referrer">referrer.</param>
        /// <param name="redemptions">redemptions.</param>
        /// <param name="items">Array of items applied to the order. It can include up to 500 items..</param>
        public ClientRedemptionsRedeemResponseBodyOrder(string id = default(string), string sourceId = default(string), StatusEnum? status = default(StatusEnum?), int? amount = default(int?), int? initialAmount = default(int?), int? discountAmount = default(int?), int? itemsDiscountAmount = default(int?), int? totalDiscountAmount = default(int?), int? totalAmount = default(int?), int? appliedDiscountAmount = default(int?), int? itemsAppliedDiscountAmount = default(int?), int? totalAppliedDiscountAmount = default(int?), Object metadata = default(Object), ObjectEnum? varObject = ObjectEnum.Order, DateTimeOffset? createdAt = default(DateTimeOffset?), DateTimeOffset? updatedAt = default(DateTimeOffset?), string customerId = default(string), string referrerId = default(string), CustomerId customer = default(CustomerId), ReferrerId referrer = default(ReferrerId), Dictionary<string, OrderRedemptionsEntry> redemptions = default(Dictionary<string, OrderRedemptionsEntry>), List<ClientRedemptionsRedeemResponseBodyOrderItemsItem> items = default(List<ClientRedemptionsRedeemResponseBodyOrderItemsItem>))
        {
            this._Id = id;
            if (this.Id != null)
            {
                this._flagId = true;
            }
            this._SourceId = sourceId;
            if (this.SourceId != null)
            {
                this._flagSourceId = true;
            }
            this._Status = status;
            if (this.Status != null)
            {
                this._flagStatus = true;
            }
            this._Amount = amount;
            if (this.Amount != null)
            {
                this._flagAmount = true;
            }
            this._InitialAmount = initialAmount;
            if (this.InitialAmount != null)
            {
                this._flagInitialAmount = true;
            }
            this._DiscountAmount = discountAmount;
            if (this.DiscountAmount != null)
            {
                this._flagDiscountAmount = true;
            }
            this._ItemsDiscountAmount = itemsDiscountAmount;
            if (this.ItemsDiscountAmount != null)
            {
                this._flagItemsDiscountAmount = true;
            }
            this._TotalDiscountAmount = totalDiscountAmount;
            if (this.TotalDiscountAmount != null)
            {
                this._flagTotalDiscountAmount = true;
            }
            this._TotalAmount = totalAmount;
            if (this.TotalAmount != null)
            {
                this._flagTotalAmount = true;
            }
            this._AppliedDiscountAmount = appliedDiscountAmount;
            if (this.AppliedDiscountAmount != null)
            {
                this._flagAppliedDiscountAmount = true;
            }
            this._ItemsAppliedDiscountAmount = itemsAppliedDiscountAmount;
            if (this.ItemsAppliedDiscountAmount != null)
            {
                this._flagItemsAppliedDiscountAmount = true;
            }
            this._TotalAppliedDiscountAmount = totalAppliedDiscountAmount;
            if (this.TotalAppliedDiscountAmount != null)
            {
                this._flagTotalAppliedDiscountAmount = true;
            }
            this._Metadata = metadata;
            if (this.Metadata != null)
            {
                this._flagMetadata = true;
            }
            this._CreatedAt = createdAt;
            if (this.CreatedAt != null)
            {
                this._flagCreatedAt = true;
            }
            this._UpdatedAt = updatedAt;
            if (this.UpdatedAt != null)
            {
                this._flagUpdatedAt = true;
            }
            this._CustomerId = customerId;
            if (this.CustomerId != null)
            {
                this._flagCustomerId = true;
            }
            this._ReferrerId = referrerId;
            if (this.ReferrerId != null)
            {
                this._flagReferrerId = true;
            }
            this._Customer = customer;
            if (this.Customer != null)
            {
                this._flagCustomer = true;
            }
            this._Referrer = referrer;
            if (this.Referrer != null)
            {
                this._flagReferrer = true;
            }
            this._Redemptions = redemptions;
            if (this.Redemptions != null)
            {
                this._flagRedemptions = true;
            }
            this._Items = items;
            if (this.Items != null)
            {
                this._flagItems = true;
            }
        }

        /// <summary>
        /// Unique ID assigned by Voucherify of an existing order that will be linked to the redemption of this request.
        /// </summary>
        /// <value>Unique ID assigned by Voucherify of an existing order that will be linked to the redemption of this request.</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id
        {
            get{ return _Id;}
            set
            {
                _Id = value;
                _flagId = true;
            }
        }
        private string _Id;
        private bool _flagId;

        /// <summary>
        /// Returns false as Id should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeId()
        {
            return _flagId;
        }
        /// <summary>
        /// Unique source ID of an existing order that will be linked to the redemption of this request.
        /// </summary>
        /// <value>Unique source ID of an existing order that will be linked to the redemption of this request.</value>
        [DataMember(Name = "source_id", EmitDefaultValue = true)]
        public string SourceId
        {
            get{ return _SourceId;}
            set
            {
                _SourceId = value;
                _flagSourceId = true;
            }
        }
        private string _SourceId;
        private bool _flagSourceId;

        /// <summary>
        /// Returns false as SourceId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSourceId()
        {
            return _flagSourceId;
        }
        /// <summary>
        /// This is the sum of the order items&#39; amounts. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).
        /// </summary>
        /// <value>This is the sum of the order items&#39; amounts. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).</value>
        [DataMember(Name = "amount", EmitDefaultValue = true)]
        public int? Amount
        {
            get{ return _Amount;}
            set
            {
                _Amount = value;
                _flagAmount = true;
            }
        }
        private int? _Amount;
        private bool _flagAmount;

        /// <summary>
        /// Returns false as Amount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAmount()
        {
            return _flagAmount;
        }
        /// <summary>
        /// This is the sum of the order items&#39; amounts before any discount or other effect (e.g. add missing units) is applied. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).
        /// </summary>
        /// <value>This is the sum of the order items&#39; amounts before any discount or other effect (e.g. add missing units) is applied. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).</value>
        [DataMember(Name = "initial_amount", EmitDefaultValue = true)]
        public int? InitialAmount
        {
            get{ return _InitialAmount;}
            set
            {
                _InitialAmount = value;
                _flagInitialAmount = true;
            }
        }
        private int? _InitialAmount;
        private bool _flagInitialAmount;

        /// <summary>
        /// Returns false as InitialAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInitialAmount()
        {
            return _flagInitialAmount;
        }
        /// <summary>
        /// Sum of all order-level discounts applied to the order. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).
        /// </summary>
        /// <value>Sum of all order-level discounts applied to the order. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).</value>
        [DataMember(Name = "discount_amount", EmitDefaultValue = true)]
        public int? DiscountAmount
        {
            get{ return _DiscountAmount;}
            set
            {
                _DiscountAmount = value;
                _flagDiscountAmount = true;
            }
        }
        private int? _DiscountAmount;
        private bool _flagDiscountAmount;

        /// <summary>
        /// Returns false as DiscountAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDiscountAmount()
        {
            return _flagDiscountAmount;
        }
        /// <summary>
        /// Sum of all product-specific discounts applied to the order. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).
        /// </summary>
        /// <value>Sum of all product-specific discounts applied to the order. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).</value>
        [DataMember(Name = "items_discount_amount", EmitDefaultValue = true)]
        public int? ItemsDiscountAmount
        {
            get{ return _ItemsDiscountAmount;}
            set
            {
                _ItemsDiscountAmount = value;
                _flagItemsDiscountAmount = true;
            }
        }
        private int? _ItemsDiscountAmount;
        private bool _flagItemsDiscountAmount;

        /// <summary>
        /// Returns false as ItemsDiscountAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeItemsDiscountAmount()
        {
            return _flagItemsDiscountAmount;
        }
        /// <summary>
        /// Sum of all order-level AND all product-specific discounts applied to the order. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).
        /// </summary>
        /// <value>Sum of all order-level AND all product-specific discounts applied to the order. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).</value>
        [DataMember(Name = "total_discount_amount", EmitDefaultValue = true)]
        public int? TotalDiscountAmount
        {
            get{ return _TotalDiscountAmount;}
            set
            {
                _TotalDiscountAmount = value;
                _flagTotalDiscountAmount = true;
            }
        }
        private int? _TotalDiscountAmount;
        private bool _flagTotalDiscountAmount;

        /// <summary>
        /// Returns false as TotalDiscountAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTotalDiscountAmount()
        {
            return _flagTotalDiscountAmount;
        }
        /// <summary>
        /// Order amount after undoing all the discounts through the rollback redemption. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).
        /// </summary>
        /// <value>Order amount after undoing all the discounts through the rollback redemption. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).</value>
        [DataMember(Name = "total_amount", EmitDefaultValue = true)]
        public int? TotalAmount
        {
            get{ return _TotalAmount;}
            set
            {
                _TotalAmount = value;
                _flagTotalAmount = true;
            }
        }
        private int? _TotalAmount;
        private bool _flagTotalAmount;

        /// <summary>
        /// Returns false as TotalAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTotalAmount()
        {
            return _flagTotalAmount;
        }
        /// <summary>
        /// This field shows the order-level discount applied. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).
        /// </summary>
        /// <value>This field shows the order-level discount applied. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).</value>
        [DataMember(Name = "applied_discount_amount", EmitDefaultValue = true)]
        public int? AppliedDiscountAmount
        {
            get{ return _AppliedDiscountAmount;}
            set
            {
                _AppliedDiscountAmount = value;
                _flagAppliedDiscountAmount = true;
            }
        }
        private int? _AppliedDiscountAmount;
        private bool _flagAppliedDiscountAmount;

        /// <summary>
        /// Returns false as AppliedDiscountAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAppliedDiscountAmount()
        {
            return _flagAppliedDiscountAmount;
        }
        /// <summary>
        /// Sum of all product-specific discounts applied in a particular request. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).   &#x60;sum(items, i &#x3D;&gt; i.applied_discount_amount)&#x60;
        /// </summary>
        /// <value>Sum of all product-specific discounts applied in a particular request. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).   &#x60;sum(items, i &#x3D;&gt; i.applied_discount_amount)&#x60;</value>
        [DataMember(Name = "items_applied_discount_amount", EmitDefaultValue = true)]
        public int? ItemsAppliedDiscountAmount
        {
            get{ return _ItemsAppliedDiscountAmount;}
            set
            {
                _ItemsAppliedDiscountAmount = value;
                _flagItemsAppliedDiscountAmount = true;
            }
        }
        private int? _ItemsAppliedDiscountAmount;
        private bool _flagItemsAppliedDiscountAmount;

        /// <summary>
        /// Returns false as ItemsAppliedDiscountAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeItemsAppliedDiscountAmount()
        {
            return _flagItemsAppliedDiscountAmount;
        }
        /// <summary>
        /// Sum of all order-level AND all product-specific discounts applied in a particular request. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).   &#x60;total_applied_discount_amount&#x60; &#x3D; &#x60;applied_discount_amount&#x60; + &#x60;items_applied_discount_amount&#x60;
        /// </summary>
        /// <value>Sum of all order-level AND all product-specific discounts applied in a particular request. It is expressed as an integer in the smallest currency unit (e.g. 100 cents for $1.00).   &#x60;total_applied_discount_amount&#x60; &#x3D; &#x60;applied_discount_amount&#x60; + &#x60;items_applied_discount_amount&#x60;</value>
        [DataMember(Name = "total_applied_discount_amount", EmitDefaultValue = true)]
        public int? TotalAppliedDiscountAmount
        {
            get{ return _TotalAppliedDiscountAmount;}
            set
            {
                _TotalAppliedDiscountAmount = value;
                _flagTotalAppliedDiscountAmount = true;
            }
        }
        private int? _TotalAppliedDiscountAmount;
        private bool _flagTotalAppliedDiscountAmount;

        /// <summary>
        /// Returns false as TotalAppliedDiscountAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTotalAppliedDiscountAmount()
        {
            return _flagTotalAppliedDiscountAmount;
        }
        /// <summary>
        /// A set of custom key/value pairs that you can attach to an order. It can be useful for storing additional information about the order in a structured format. It can be used to define business validation rules or discount formulas.
        /// </summary>
        /// <value>A set of custom key/value pairs that you can attach to an order. It can be useful for storing additional information about the order in a structured format. It can be used to define business validation rules or discount formulas.</value>
        [DataMember(Name = "metadata", EmitDefaultValue = true)]
        public Object Metadata
        {
            get{ return _Metadata;}
            set
            {
                _Metadata = value;
                _flagMetadata = true;
            }
        }
        private Object _Metadata;
        private bool _flagMetadata;

        /// <summary>
        /// Returns false as Metadata should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMetadata()
        {
            return _flagMetadata;
        }
        /// <summary>
        /// Timestamp representing the date and time when the order was created. The value is shown in the ISO 8601 format.
        /// </summary>
        /// <value>Timestamp representing the date and time when the order was created. The value is shown in the ISO 8601 format.</value>
        /*
        <example>2021-12-22T10:13:06.487Z</example>
        */
        [DataMember(Name = "created_at", EmitDefaultValue = true)]
        public DateTimeOffset? CreatedAt
        {
            get{ return _CreatedAt;}
            set
            {
                _CreatedAt = value;
                _flagCreatedAt = true;
            }
        }
        private DateTimeOffset? _CreatedAt;
        private bool _flagCreatedAt;

        /// <summary>
        /// Returns false as CreatedAt should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCreatedAt()
        {
            return _flagCreatedAt;
        }
        /// <summary>
        /// Timestamp representing the date and time when the order was last updated in ISO 8601 format.
        /// </summary>
        /// <value>Timestamp representing the date and time when the order was last updated in ISO 8601 format.</value>
        /*
        <example>2021-12-22T10:14:45.316Z</example>
        */
        [DataMember(Name = "updated_at", EmitDefaultValue = true)]
        public DateTimeOffset? UpdatedAt
        {
            get{ return _UpdatedAt;}
            set
            {
                _UpdatedAt = value;
                _flagUpdatedAt = true;
            }
        }
        private DateTimeOffset? _UpdatedAt;
        private bool _flagUpdatedAt;

        /// <summary>
        /// Returns false as UpdatedAt should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeUpdatedAt()
        {
            return _flagUpdatedAt;
        }
        /// <summary>
        /// Unique customer identifier of the customer making the purchase. The ID is assigned by Voucherify.
        /// </summary>
        /// <value>Unique customer identifier of the customer making the purchase. The ID is assigned by Voucherify.</value>
        /*
        <example>cust_7iUa6ICKyU6gH40dBU25kQU1</example>
        */
        [DataMember(Name = "customer_id", EmitDefaultValue = true)]
        public string CustomerId
        {
            get{ return _CustomerId;}
            set
            {
                _CustomerId = value;
                _flagCustomerId = true;
            }
        }
        private string _CustomerId;
        private bool _flagCustomerId;

        /// <summary>
        /// Returns false as CustomerId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCustomerId()
        {
            return _flagCustomerId;
        }
        /// <summary>
        /// Unique referrer ID.
        /// </summary>
        /// <value>Unique referrer ID.</value>
        /*
        <example>cust_nM4jqPiaXUvQdVSA6vTRUnix</example>
        */
        [DataMember(Name = "referrer_id", EmitDefaultValue = true)]
        public string ReferrerId
        {
            get{ return _ReferrerId;}
            set
            {
                _ReferrerId = value;
                _flagReferrerId = true;
            }
        }
        private string _ReferrerId;
        private bool _flagReferrerId;

        /// <summary>
        /// Returns false as ReferrerId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeReferrerId()
        {
            return _flagReferrerId;
        }
        /// <summary>
        /// Gets or Sets Customer
        /// </summary>
        [DataMember(Name = "customer", EmitDefaultValue = true)]
        public CustomerId Customer
        {
            get{ return _Customer;}
            set
            {
                _Customer = value;
                _flagCustomer = true;
            }
        }
        private CustomerId _Customer;
        private bool _flagCustomer;

        /// <summary>
        /// Returns false as Customer should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCustomer()
        {
            return _flagCustomer;
        }
        /// <summary>
        /// Gets or Sets Referrer
        /// </summary>
        [DataMember(Name = "referrer", EmitDefaultValue = true)]
        public ReferrerId Referrer
        {
            get{ return _Referrer;}
            set
            {
                _Referrer = value;
                _flagReferrer = true;
            }
        }
        private ReferrerId _Referrer;
        private bool _flagReferrer;

        /// <summary>
        /// Returns false as Referrer should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeReferrer()
        {
            return _flagReferrer;
        }
        /// <summary>
        /// Gets or Sets Redemptions
        /// </summary>
        [DataMember(Name = "redemptions", EmitDefaultValue = true)]
        public Dictionary<string, OrderRedemptionsEntry> Redemptions
        {
            get{ return _Redemptions;}
            set
            {
                _Redemptions = value;
                _flagRedemptions = true;
            }
        }
        private Dictionary<string, OrderRedemptionsEntry> _Redemptions;
        private bool _flagRedemptions;

        /// <summary>
        /// Returns false as Redemptions should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRedemptions()
        {
            return _flagRedemptions;
        }
        /// <summary>
        /// Array of items applied to the order. It can include up to 500 items.
        /// </summary>
        /// <value>Array of items applied to the order. It can include up to 500 items.</value>
        [DataMember(Name = "items", EmitDefaultValue = true)]
        public List<ClientRedemptionsRedeemResponseBodyOrderItemsItem> Items
        {
            get{ return _Items;}
            set
            {
                _Items = value;
                _flagItems = true;
            }
        }
        private List<ClientRedemptionsRedeemResponseBodyOrderItemsItem> _Items;
        private bool _flagItems;

        /// <summary>
        /// Returns false as Items should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeItems()
        {
            return _flagItems;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ClientRedemptionsRedeemResponseBodyOrder {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SourceId: ").Append(SourceId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  InitialAmount: ").Append(InitialAmount).Append("\n");
            sb.Append("  DiscountAmount: ").Append(DiscountAmount).Append("\n");
            sb.Append("  ItemsDiscountAmount: ").Append(ItemsDiscountAmount).Append("\n");
            sb.Append("  TotalDiscountAmount: ").Append(TotalDiscountAmount).Append("\n");
            sb.Append("  TotalAmount: ").Append(TotalAmount).Append("\n");
            sb.Append("  AppliedDiscountAmount: ").Append(AppliedDiscountAmount).Append("\n");
            sb.Append("  ItemsAppliedDiscountAmount: ").Append(ItemsAppliedDiscountAmount).Append("\n");
            sb.Append("  TotalAppliedDiscountAmount: ").Append(TotalAppliedDiscountAmount).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Object: ").Append(Object).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  ReferrerId: ").Append(ReferrerId).Append("\n");
            sb.Append("  Customer: ").Append(Customer).Append("\n");
            sb.Append("  Referrer: ").Append(Referrer).Append("\n");
            sb.Append("  Redemptions: ").Append(Redemptions).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
