/*
 * Voucherify API
 *
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Voucherify.Client.OpenAPIDateConverter;
using Voucherify.Client;

namespace Voucherify.Model
{
    /// <summary>
    /// Parameter to return details about &#x60;locked_credits&#x60; on a gift card which has locked credits under a validation session.
    /// </summary>
    [DataContract(Name = "ClientQualificationsCheckEligibilityRequestBodySession")]
    public partial class ClientQualificationsCheckEligibilityRequestBodySession : IValidatableObject
    {
        /// <summary>
        /// Parameter required to return the details about the &#x60;locked_credits&#x60;.
        /// </summary>
        /// <value>Parameter required to return the details about the &#x60;locked_credits&#x60;.</value>
        [JsonConverter(typeof(SafeEnumConverter<TypeEnum>))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum LOCK for value: LOCK
            /// </summary>
            [EnumMember(Value = "LOCK")]
            LOCK = 1
        }


        /// <summary>
        /// Parameter required to return the details about the &#x60;locked_credits&#x60;.
        /// </summary>
        /// <value>Parameter required to return the details about the &#x60;locked_credits&#x60;.</value>

        [JsonConverter(typeof(SafeEnumConverter<TypeEnum>))]
        [DataMember(Name = "type", EmitDefaultValue = true)]
        public TypeEnum? Type
        {
            get{ return _Type;}
            set
            {
                _Type = value;
                _flagType = true;
            }
        }
        private TypeEnum? _Type;
        private bool _flagType;

        /// <summary>
        /// Returns false as Type should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeType()
        {
            return _flagType;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="ClientQualificationsCheckEligibilityRequestBodySession" /> class.
        /// </summary>
        /// <param name="type">Parameter required to return the details about the &#x60;locked_credits&#x60;..</param>
        public ClientQualificationsCheckEligibilityRequestBodySession(TypeEnum? type = default(TypeEnum?))
        {
            this._Type = type;
            if (this.Type != null)
            {
                this._flagType = true;
            }
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ClientQualificationsCheckEligibilityRequestBodySession {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
