/*
 * Voucherify API
 *
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Voucherify.Client.OpenAPIDateConverter;

namespace Voucherify.Model
{
    /// <summary>
    /// Stores Quick Response (QR) representation of encrypted code.
    /// </summary>
    [DataContract(Name = "LoyaltiesMembersTransfersCreateResponseBodyAssetsQr")]
    public partial class LoyaltiesMembersTransfersCreateResponseBodyAssetsQr : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoyaltiesMembersTransfersCreateResponseBodyAssetsQr" /> class.
        /// </summary>
        /// <param name="id">Encrypted voucher code ID..</param>
        /// <param name="url">URL to QR code    *Optional:* Attach query parameters to base URL to customize the image of the encrypted voucher code.    - &#x60;size&#x60;: integer value from &#x60;1&#x60; to &#x60;100&#x60;   - &#x60;format&#x60;: string, either &#x60;png&#x60; (default) or &#x60;svg&#x60;.</param>
        public LoyaltiesMembersTransfersCreateResponseBodyAssetsQr(string id = default(string), string url = default(string))
        {
            this._Id = id;
            if (this.Id != null)
            {
                this._flagId = true;
            }
            this._Url = url;
            if (this.Url != null)
            {
                this._flagUrl = true;
            }
        }

        /// <summary>
        /// Encrypted voucher code ID.
        /// </summary>
        /// <value>Encrypted voucher code ID.</value>
        /*
        <example>U2FsdGVkX19ucFhvVmBVpVYG5KoswTsjSIaqoKg5L9ie4BK+t4pp7U7oFzjGJzj9q/bmuMOj9mEFiVKDMIkSaruKedMvHbKoPX5Sg+BaZk5QwXMf8k/OzSlOEVybpwSq+AiqPoNtjeuqtIgkDyvT6Q&#x3D;&#x3D;</example>
        */
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string Id
        {
            get{ return _Id;}
            set
            {
                _Id = value;
                _flagId = true;
            }
        }
        private string _Id;
        private bool _flagId;

        /// <summary>
        /// Returns false as Id should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeId()
        {
            return _flagId;
        }
        /// <summary>
        /// URL to QR code    *Optional:* Attach query parameters to base URL to customize the image of the encrypted voucher code.    - &#x60;size&#x60;: integer value from &#x60;1&#x60; to &#x60;100&#x60;   - &#x60;format&#x60;: string, either &#x60;png&#x60; (default) or &#x60;svg&#x60;
        /// </summary>
        /// <value>URL to QR code    *Optional:* Attach query parameters to base URL to customize the image of the encrypted voucher code.    - &#x60;size&#x60;: integer value from &#x60;1&#x60; to &#x60;100&#x60;   - &#x60;format&#x60;: string, either &#x60;png&#x60; (default) or &#x60;svg&#x60;</value>
        /*
        <example>https://dev.dl.voucherify.io/api/v1/assets/qr/U2FsdGVkX19ucFhvVmBVpVYG5KoswTsjSIaqoKg5L9ie4BK%2Bt4pp7U7oFzjGJzj9q%2FbmuMOj9mEFiVKDMIkSaruKedMvHbKoPX5Sg%2BBaZk5QwXMf8k%2FOzSlOEVybpwSq%2BAiqPoNtjeuqtIgkDyvT6Q%3D%3D</example>
        */
        [DataMember(Name = "url", EmitDefaultValue = true)]
        public string Url
        {
            get{ return _Url;}
            set
            {
                _Url = value;
                _flagUrl = true;
            }
        }
        private string _Url;
        private bool _flagUrl;

        /// <summary>
        /// Returns false as Url should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeUrl()
        {
            return _flagUrl;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoyaltiesMembersTransfersCreateResponseBodyAssetsQr {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
