/*
 * Voucherify API
 *
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Voucherify.Client.OpenAPIDateConverter;

namespace Voucherify.Model
{
    /// <summary>
    /// Defines the details of the channel through which the redemption was issued.
    /// </summary>
    [DataContract(Name = "LoyaltiesMembersRedemptionRedeemResponseBodyChannel")]
    public partial class LoyaltiesMembersRedemptionRedeemResponseBodyChannel : IValidatableObject
    {
        /// <summary>
        /// The source of the channel for the redemption. A &#x60;USER&#x60; corresponds to the Voucherify Dashboard, &#x60;API&#x60; corresponds to the API, and &#x60;AUTO_REDEEM&#x60; corresponds to a loyalty campaign reward that has been redeemed automatically.
        /// </summary>
        /// <value>The source of the channel for the redemption. A &#x60;USER&#x60; corresponds to the Voucherify Dashboard, &#x60;API&#x60; corresponds to the API, and &#x60;AUTO_REDEEM&#x60; corresponds to a loyalty campaign reward that has been redeemed automatically.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ChannelTypeEnum
        {
            /// <summary>
            /// Enum USER for value: USER
            /// </summary>
            [EnumMember(Value = "USER")]
            USER = 1,

            /// <summary>
            /// Enum API for value: API
            /// </summary>
            [EnumMember(Value = "API")]
            API = 2,

            /// <summary>
            /// Enum AUTOREDEEM for value: AUTO_REDEEM
            /// </summary>
            [EnumMember(Value = "AUTO_REDEEM")]
            AUTOREDEEM = 3
        }


        /// <summary>
        /// The source of the channel for the redemption. A &#x60;USER&#x60; corresponds to the Voucherify Dashboard, &#x60;API&#x60; corresponds to the API, and &#x60;AUTO_REDEEM&#x60; corresponds to a loyalty campaign reward that has been redeemed automatically.
        /// </summary>
        /// <value>The source of the channel for the redemption. A &#x60;USER&#x60; corresponds to the Voucherify Dashboard, &#x60;API&#x60; corresponds to the API, and &#x60;AUTO_REDEEM&#x60; corresponds to a loyalty campaign reward that has been redeemed automatically.</value>

        [DataMember(Name = "channel_type", EmitDefaultValue = true)]
        public ChannelTypeEnum? ChannelType
        {
            get{ return _ChannelType;}
            set
            {
                _ChannelType = value;
                _flagChannelType = true;
            }
        }
        private ChannelTypeEnum? _ChannelType;
        private bool _flagChannelType;

        /// <summary>
        /// Returns false as ChannelType should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeChannelType()
        {
            return _flagChannelType;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="LoyaltiesMembersRedemptionRedeemResponseBodyChannel" /> class.
        /// </summary>
        /// <param name="channelId">Unique channel ID of the user performing the redemption. This is either a user ID from a user using the Voucherify Dashboard or an X-APP-Id of a user using the API. For &#x60;AUTO_REDEEM&#x60;, it is the reward assignment ID..</param>
        /// <param name="channelType">The source of the channel for the redemption. A &#x60;USER&#x60; corresponds to the Voucherify Dashboard, &#x60;API&#x60; corresponds to the API, and &#x60;AUTO_REDEEM&#x60; corresponds to a loyalty campaign reward that has been redeemed automatically..</param>
        public LoyaltiesMembersRedemptionRedeemResponseBodyChannel(string channelId = default(string), ChannelTypeEnum? channelType = default(ChannelTypeEnum?))
        {
            this._ChannelId = channelId;
            if (this.ChannelId != null)
            {
                this._flagChannelId = true;
            }
            this._ChannelType = channelType;
            if (this.ChannelType != null)
            {
                this._flagChannelType = true;
            }
        }

        /// <summary>
        /// Unique channel ID of the user performing the redemption. This is either a user ID from a user using the Voucherify Dashboard or an X-APP-Id of a user using the API. For &#x60;AUTO_REDEEM&#x60;, it is the reward assignment ID.
        /// </summary>
        /// <value>Unique channel ID of the user performing the redemption. This is either a user ID from a user using the Voucherify Dashboard or an X-APP-Id of a user using the API. For &#x60;AUTO_REDEEM&#x60;, it is the reward assignment ID.</value>
        /*
        <example>user_g24UoRO3Caxu7FCT4n5tpYEa3zUG0FrH</example>
        */
        [DataMember(Name = "channel_id", EmitDefaultValue = true)]
        public string ChannelId
        {
            get{ return _ChannelId;}
            set
            {
                _ChannelId = value;
                _flagChannelId = true;
            }
        }
        private string _ChannelId;
        private bool _flagChannelId;

        /// <summary>
        /// Returns false as ChannelId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeChannelId()
        {
            return _flagChannelId;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoyaltiesMembersRedemptionRedeemResponseBodyChannel {\n");
            sb.Append("  ChannelId: ").Append(ChannelId).Append("\n");
            sb.Append("  ChannelType: ").Append(ChannelType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
