/*
 * Voucherify API
 *
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Voucherify.Client.OpenAPIDateConverter;

namespace Voucherify.Model
{
    /// <summary>
    /// Determines the character set that is used as default for vouchers. It is affected by the &#x60;\&quot;case_sensitive_codes\&quot;&#x60; setting.
    /// </summary>
    [DataContract(Name = "ManagementProjectsUpdateRequestBodyDefaultCodeConfig")]
    public partial class ManagementProjectsUpdateRequestBodyDefaultCodeConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ManagementProjectsUpdateRequestBodyDefaultCodeConfig" /> class.
        /// </summary>
        /// <param name="charset">Lists all characters that are used as default for vouchers.</param>
        public ManagementProjectsUpdateRequestBodyDefaultCodeConfig(string charset = default(string))
        {
            this._Charset = charset;
            if (this.Charset != null)
            {
                this._flagCharset = true;
            }
        }

        /// <summary>
        /// Lists all characters that are used as default for vouchers
        /// </summary>
        /// <value>Lists all characters that are used as default for vouchers</value>
        [DataMember(Name = "charset", EmitDefaultValue = true)]
        public string Charset
        {
            get{ return _Charset;}
            set
            {
                _Charset = value;
                _flagCharset = true;
            }
        }
        private string _Charset;
        private bool _flagCharset;

        /// <summary>
        /// Returns false as Charset should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCharset()
        {
            return _flagCharset;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ManagementProjectsUpdateRequestBodyDefaultCodeConfig {\n");
            sb.Append("  Charset: ").Append(Charset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
