/*
 * Voucherify API
 *
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Voucherify.Client.OpenAPIDateConverter;

namespace Voucherify.Model
{
    /// <summary>
    /// OrderItem
    /// </summary>
    [DataContract(Name = "OrderItem")]
    public partial class OrderItem : IValidatableObject
    {
        /// <summary>
        /// Used along with the source_id property, can be set to either sku or product.
        /// </summary>
        /// <value>Used along with the source_id property, can be set to either sku or product.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RelatedObjectEnum
        {
            /// <summary>
            /// Enum Product for value: product
            /// </summary>
            [EnumMember(Value = "product")]
            Product = 1,

            /// <summary>
            /// Enum Sku for value: sku
            /// </summary>
            [EnumMember(Value = "sku")]
            Sku = 2
        }


        /// <summary>
        /// Used along with the source_id property, can be set to either sku or product.
        /// </summary>
        /// <value>Used along with the source_id property, can be set to either sku or product.</value>

        [DataMember(Name = "related_object", EmitDefaultValue = true)]
        public RelatedObjectEnum? RelatedObject
        {
            get{ return _RelatedObject;}
            set
            {
                _RelatedObject = value;
                _flagRelatedObject = true;
            }
        }
        private RelatedObjectEnum? _RelatedObject;
        private bool _flagRelatedObject;

        /// <summary>
        /// Returns false as RelatedObject should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRelatedObject()
        {
            return _flagRelatedObject;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderItem" /> class.
        /// </summary>
        /// <param name="skuId">Unique identifier of the SKU. It is assigned by Voucherify..</param>
        /// <param name="productId">Unique identifier of the product. It is assigned by Voucherify..</param>
        /// <param name="relatedObject">Used along with the source_id property, can be set to either sku or product..</param>
        /// <param name="sourceId">The merchant&#39;s product/SKU ID (if it is different from the Voucherify product/SKU ID). It is useful in the integration between multiple systems. It can be an ID from an eCommerce site, a database, or a third-party service..</param>
        /// <param name="quantity">The quantity of the particular item in the cart..</param>
        /// <param name="discountQuantity">Number of dicounted items..</param>
        /// <param name="initialQuantity">A positive integer in the smallest unit quantity representing the total amount of the order; this is the sum of the order items&#39; quantity..</param>
        /// <param name="amount">The total amount of the order item (price * quantity)..</param>
        /// <param name="discountAmount">Sum of all order-item-level discounts applied to the order..</param>
        /// <param name="initialAmount">A positive integer in the smallest currency unit (e.g. 100 cents for $1.00) representing the total amount of the order. This is the sum of the order items&#39; amounts..</param>
        /// <param name="price">Unit price of an item. The value is multiplied by 100 to represent 2 decimal places. For example &#x60;10000 cents&#x60; for &#x60;$100.00&#x60;..</param>
        /// <param name="product">product.</param>
        /// <param name="sku">sku.</param>
        /// <param name="metadata">A set of custom key/value pairs that you can attach to an order item. It can be useful for storing additional information about the order item in a structured format. It can be used to define business validation rules..</param>
        public OrderItem(string skuId = default(string), string productId = default(string), RelatedObjectEnum? relatedObject = default(RelatedObjectEnum?), string sourceId = default(string), int? quantity = default(int?), int? discountQuantity = default(int?), int? initialQuantity = default(int?), int? amount = default(int?), int? discountAmount = default(int?), int? initialAmount = default(int?), int? price = default(int?), OrderItemProduct product = default(OrderItemProduct), OrderItemSku sku = default(OrderItemSku), Object metadata = default(Object))
        {
            this._SkuId = skuId;
            if (this.SkuId != null)
            {
                this._flagSkuId = true;
            }
            this._ProductId = productId;
            if (this.ProductId != null)
            {
                this._flagProductId = true;
            }
            this._RelatedObject = relatedObject;
            if (this.RelatedObject != null)
            {
                this._flagRelatedObject = true;
            }
            this._SourceId = sourceId;
            if (this.SourceId != null)
            {
                this._flagSourceId = true;
            }
            this._Quantity = quantity;
            if (this.Quantity != null)
            {
                this._flagQuantity = true;
            }
            this._DiscountQuantity = discountQuantity;
            if (this.DiscountQuantity != null)
            {
                this._flagDiscountQuantity = true;
            }
            this._InitialQuantity = initialQuantity;
            if (this.InitialQuantity != null)
            {
                this._flagInitialQuantity = true;
            }
            this._Amount = amount;
            if (this.Amount != null)
            {
                this._flagAmount = true;
            }
            this._DiscountAmount = discountAmount;
            if (this.DiscountAmount != null)
            {
                this._flagDiscountAmount = true;
            }
            this._InitialAmount = initialAmount;
            if (this.InitialAmount != null)
            {
                this._flagInitialAmount = true;
            }
            this._Price = price;
            if (this.Price != null)
            {
                this._flagPrice = true;
            }
            this._Product = product;
            if (this.Product != null)
            {
                this._flagProduct = true;
            }
            this._Sku = sku;
            if (this.Sku != null)
            {
                this._flagSku = true;
            }
            this._Metadata = metadata;
            if (this.Metadata != null)
            {
                this._flagMetadata = true;
            }
        }

        /// <summary>
        /// Unique identifier of the SKU. It is assigned by Voucherify.
        /// </summary>
        /// <value>Unique identifier of the SKU. It is assigned by Voucherify.</value>
        [DataMember(Name = "sku_id", EmitDefaultValue = true)]
        public string SkuId
        {
            get{ return _SkuId;}
            set
            {
                _SkuId = value;
                _flagSkuId = true;
            }
        }
        private string _SkuId;
        private bool _flagSkuId;

        /// <summary>
        /// Returns false as SkuId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSkuId()
        {
            return _flagSkuId;
        }
        /// <summary>
        /// Unique identifier of the product. It is assigned by Voucherify.
        /// </summary>
        /// <value>Unique identifier of the product. It is assigned by Voucherify.</value>
        [DataMember(Name = "product_id", EmitDefaultValue = true)]
        public string ProductId
        {
            get{ return _ProductId;}
            set
            {
                _ProductId = value;
                _flagProductId = true;
            }
        }
        private string _ProductId;
        private bool _flagProductId;

        /// <summary>
        /// Returns false as ProductId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeProductId()
        {
            return _flagProductId;
        }
        /// <summary>
        /// The merchant&#39;s product/SKU ID (if it is different from the Voucherify product/SKU ID). It is useful in the integration between multiple systems. It can be an ID from an eCommerce site, a database, or a third-party service.
        /// </summary>
        /// <value>The merchant&#39;s product/SKU ID (if it is different from the Voucherify product/SKU ID). It is useful in the integration between multiple systems. It can be an ID from an eCommerce site, a database, or a third-party service.</value>
        [DataMember(Name = "source_id", EmitDefaultValue = true)]
        public string SourceId
        {
            get{ return _SourceId;}
            set
            {
                _SourceId = value;
                _flagSourceId = true;
            }
        }
        private string _SourceId;
        private bool _flagSourceId;

        /// <summary>
        /// Returns false as SourceId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSourceId()
        {
            return _flagSourceId;
        }
        /// <summary>
        /// The quantity of the particular item in the cart.
        /// </summary>
        /// <value>The quantity of the particular item in the cart.</value>
        [DataMember(Name = "quantity", EmitDefaultValue = true)]
        public int? Quantity
        {
            get{ return _Quantity;}
            set
            {
                _Quantity = value;
                _flagQuantity = true;
            }
        }
        private int? _Quantity;
        private bool _flagQuantity;

        /// <summary>
        /// Returns false as Quantity should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeQuantity()
        {
            return _flagQuantity;
        }
        /// <summary>
        /// Number of dicounted items.
        /// </summary>
        /// <value>Number of dicounted items.</value>
        [DataMember(Name = "discount_quantity", EmitDefaultValue = true)]
        public int? DiscountQuantity
        {
            get{ return _DiscountQuantity;}
            set
            {
                _DiscountQuantity = value;
                _flagDiscountQuantity = true;
            }
        }
        private int? _DiscountQuantity;
        private bool _flagDiscountQuantity;

        /// <summary>
        /// Returns false as DiscountQuantity should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDiscountQuantity()
        {
            return _flagDiscountQuantity;
        }
        /// <summary>
        /// A positive integer in the smallest unit quantity representing the total amount of the order; this is the sum of the order items&#39; quantity.
        /// </summary>
        /// <value>A positive integer in the smallest unit quantity representing the total amount of the order; this is the sum of the order items&#39; quantity.</value>
        [DataMember(Name = "initial_quantity", EmitDefaultValue = true)]
        public int? InitialQuantity
        {
            get{ return _InitialQuantity;}
            set
            {
                _InitialQuantity = value;
                _flagInitialQuantity = true;
            }
        }
        private int? _InitialQuantity;
        private bool _flagInitialQuantity;

        /// <summary>
        /// Returns false as InitialQuantity should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInitialQuantity()
        {
            return _flagInitialQuantity;
        }
        /// <summary>
        /// The total amount of the order item (price * quantity).
        /// </summary>
        /// <value>The total amount of the order item (price * quantity).</value>
        [DataMember(Name = "amount", EmitDefaultValue = true)]
        public int? Amount
        {
            get{ return _Amount;}
            set
            {
                _Amount = value;
                _flagAmount = true;
            }
        }
        private int? _Amount;
        private bool _flagAmount;

        /// <summary>
        /// Returns false as Amount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAmount()
        {
            return _flagAmount;
        }
        /// <summary>
        /// Sum of all order-item-level discounts applied to the order.
        /// </summary>
        /// <value>Sum of all order-item-level discounts applied to the order.</value>
        [DataMember(Name = "discount_amount", EmitDefaultValue = true)]
        public int? DiscountAmount
        {
            get{ return _DiscountAmount;}
            set
            {
                _DiscountAmount = value;
                _flagDiscountAmount = true;
            }
        }
        private int? _DiscountAmount;
        private bool _flagDiscountAmount;

        /// <summary>
        /// Returns false as DiscountAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDiscountAmount()
        {
            return _flagDiscountAmount;
        }
        /// <summary>
        /// A positive integer in the smallest currency unit (e.g. 100 cents for $1.00) representing the total amount of the order. This is the sum of the order items&#39; amounts.
        /// </summary>
        /// <value>A positive integer in the smallest currency unit (e.g. 100 cents for $1.00) representing the total amount of the order. This is the sum of the order items&#39; amounts.</value>
        [DataMember(Name = "initial_amount", EmitDefaultValue = true)]
        public int? InitialAmount
        {
            get{ return _InitialAmount;}
            set
            {
                _InitialAmount = value;
                _flagInitialAmount = true;
            }
        }
        private int? _InitialAmount;
        private bool _flagInitialAmount;

        /// <summary>
        /// Returns false as InitialAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInitialAmount()
        {
            return _flagInitialAmount;
        }
        /// <summary>
        /// Unit price of an item. The value is multiplied by 100 to represent 2 decimal places. For example &#x60;10000 cents&#x60; for &#x60;$100.00&#x60;.
        /// </summary>
        /// <value>Unit price of an item. The value is multiplied by 100 to represent 2 decimal places. For example &#x60;10000 cents&#x60; for &#x60;$100.00&#x60;.</value>
        [DataMember(Name = "price", EmitDefaultValue = true)]
        public int? Price
        {
            get{ return _Price;}
            set
            {
                _Price = value;
                _flagPrice = true;
            }
        }
        private int? _Price;
        private bool _flagPrice;

        /// <summary>
        /// Returns false as Price should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePrice()
        {
            return _flagPrice;
        }
        /// <summary>
        /// Gets or Sets Product
        /// </summary>
        [DataMember(Name = "product", EmitDefaultValue = true)]
        public OrderItemProduct Product
        {
            get{ return _Product;}
            set
            {
                _Product = value;
                _flagProduct = true;
            }
        }
        private OrderItemProduct _Product;
        private bool _flagProduct;

        /// <summary>
        /// Returns false as Product should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeProduct()
        {
            return _flagProduct;
        }
        /// <summary>
        /// Gets or Sets Sku
        /// </summary>
        [DataMember(Name = "sku", EmitDefaultValue = true)]
        public OrderItemSku Sku
        {
            get{ return _Sku;}
            set
            {
                _Sku = value;
                _flagSku = true;
            }
        }
        private OrderItemSku _Sku;
        private bool _flagSku;

        /// <summary>
        /// Returns false as Sku should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSku()
        {
            return _flagSku;
        }
        /// <summary>
        /// A set of custom key/value pairs that you can attach to an order item. It can be useful for storing additional information about the order item in a structured format. It can be used to define business validation rules.
        /// </summary>
        /// <value>A set of custom key/value pairs that you can attach to an order item. It can be useful for storing additional information about the order item in a structured format. It can be used to define business validation rules.</value>
        [DataMember(Name = "metadata", EmitDefaultValue = true)]
        public Object Metadata
        {
            get{ return _Metadata;}
            set
            {
                _Metadata = value;
                _flagMetadata = true;
            }
        }
        private Object _Metadata;
        private bool _flagMetadata;

        /// <summary>
        /// Returns false as Metadata should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMetadata()
        {
            return _flagMetadata;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderItem {\n");
            sb.Append("  SkuId: ").Append(SkuId).Append("\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  RelatedObject: ").Append(RelatedObject).Append("\n");
            sb.Append("  SourceId: ").Append(SourceId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  DiscountQuantity: ").Append(DiscountQuantity).Append("\n");
            sb.Append("  InitialQuantity: ").Append(InitialQuantity).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  DiscountAmount: ").Append(DiscountAmount).Append("\n");
            sb.Append("  InitialAmount: ").Append(InitialAmount).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("  Sku: ").Append(Sku).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
