/*
 * Voucherify API
 *
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Voucherify.Client.OpenAPIDateConverter;

namespace Voucherify.Model
{
    /// <summary>
    /// Request body schema for **POST** &#x60;v1/referrals/{campaignId}/members/{memberId}/holders&#x60; and **POST** &#x60;v1/referrals/members/{memberId}/holders&#x60;.
    /// </summary>
    [DataContract(Name = "ReferralsMembersHoldersCreateInBulkRequestBody")]
    public partial class ReferralsMembersHoldersCreateInBulkRequestBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReferralsMembersHoldersCreateInBulkRequestBody" /> class.
        /// </summary>
        /// <param name="holders">Array of holders to be added to a referral card as referees. You have to send at least one object in the array up to a maximum of 100 objects. You can send either a &#x60;source_id&#x60; or &#x60;id&#x60;, or both; however, at least one of them is required. If both are sent, Voucherify checks &#x60;id&#x60; to upsert that customer&#39;s data..</param>
        /// <param name="metadata">A set of custom key/value pairs that you can attach to the redeemable holders sent in the array. The value can be a string, number, boolean, date, datetime, image URL, or object. The metadata must meet the metadata schema for publications. The metadata object stores all custom attributes assigned to the redeemable holder..</param>
        public ReferralsMembersHoldersCreateInBulkRequestBody(List<Customer> holders = default(List<Customer>), Object metadata = default(Object))
        {
            this._Holders = holders;
            if (this.Holders != null)
            {
                this._flagHolders = true;
            }
            this._Metadata = metadata;
            if (this.Metadata != null)
            {
                this._flagMetadata = true;
            }
        }

        /// <summary>
        /// Array of holders to be added to a referral card as referees. You have to send at least one object in the array up to a maximum of 100 objects. You can send either a &#x60;source_id&#x60; or &#x60;id&#x60;, or both; however, at least one of them is required. If both are sent, Voucherify checks &#x60;id&#x60; to upsert that customer&#39;s data.
        /// </summary>
        /// <value>Array of holders to be added to a referral card as referees. You have to send at least one object in the array up to a maximum of 100 objects. You can send either a &#x60;source_id&#x60; or &#x60;id&#x60;, or both; however, at least one of them is required. If both are sent, Voucherify checks &#x60;id&#x60; to upsert that customer&#39;s data.</value>
        [DataMember(Name = "holders", EmitDefaultValue = true)]
        public List<Customer> Holders
        {
            get{ return _Holders;}
            set
            {
                _Holders = value;
                _flagHolders = true;
            }
        }
        private List<Customer> _Holders;
        private bool _flagHolders;

        /// <summary>
        /// Returns false as Holders should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeHolders()
        {
            return _flagHolders;
        }
        /// <summary>
        /// A set of custom key/value pairs that you can attach to the redeemable holders sent in the array. The value can be a string, number, boolean, date, datetime, image URL, or object. The metadata must meet the metadata schema for publications. The metadata object stores all custom attributes assigned to the redeemable holder.
        /// </summary>
        /// <value>A set of custom key/value pairs that you can attach to the redeemable holders sent in the array. The value can be a string, number, boolean, date, datetime, image URL, or object. The metadata must meet the metadata schema for publications. The metadata object stores all custom attributes assigned to the redeemable holder.</value>
        [DataMember(Name = "metadata", EmitDefaultValue = true)]
        public Object Metadata
        {
            get{ return _Metadata;}
            set
            {
                _Metadata = value;
                _flagMetadata = true;
            }
        }
        private Object _Metadata;
        private bool _flagMetadata;

        /// <summary>
        /// Returns false as Metadata should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMetadata()
        {
            return _flagMetadata;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReferralsMembersHoldersCreateInBulkRequestBody {\n");
            sb.Append("  Holders: ").Append(Holders).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
