/*
 * Voucherify API
 *
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Voucherify.Client.OpenAPIDateConverter;
using Voucherify.Client;

namespace Voucherify.Model
{
    /// <summary>
    /// References an Error Message Library entry. Required when &#x60;mode&#x60; is &#x60;LIBRARY&#x60;. Must be omitted or &#x60;null&#x60; when &#x60;mode&#x60; is &#x60;MESSAGES&#x60;.
    /// </summary>
    [DataContract(Name = "ValidationRuleErrorLibrary")]
    public partial class ValidationRuleErrorLibrary : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationRuleErrorLibrary" /> class.
        /// </summary>
        /// <param name="key">Identifies the library message. Use a validation-rule name such as &#x60;order.amount&#x60;, or a custom attribute key such as &#x60;order.metadata.location&#x60;..</param>
        public ValidationRuleErrorLibrary(string key = default(string))
        {
            this._Key = key;
            if (this.Key != null)
            {
                this._flagKey = true;
            }
        }

        /// <summary>
        /// Identifies the library message. Use a validation-rule name such as &#x60;order.amount&#x60;, or a custom attribute key such as &#x60;order.metadata.location&#x60;.
        /// </summary>
        /// <value>Identifies the library message. Use a validation-rule name such as &#x60;order.amount&#x60;, or a custom attribute key such as &#x60;order.metadata.location&#x60;.</value>
        /*
        <example>order.amount</example>
        */
        [DataMember(Name = "key", EmitDefaultValue = true)]
        public string Key
        {
            get{ return _Key;}
            set
            {
                _Key = value;
                _flagKey = true;
            }
        }
        private string _Key;
        private bool _flagKey;

        /// <summary>
        /// Returns false as Key should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeKey()
        {
            return _flagKey;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidationRuleErrorLibrary {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Key (string) maxLength
            if (this.Key != null && this.Key.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Key, length must be less than 100.", new [] { "Key" });
            }

            yield break;
        }
    }

}
